// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBijlwWrIwNyqrrIcPxGEOaBPcj1-N04MY',
    appId: '1:81733342916:web:446e2294d4ad523238db91',
    messagingSenderId: '81733342916',
    projectId: 'e-learning-5b16a',
    authDomain: 'e-learning-5b16a.firebaseapp.com',
    storageBucket: 'e-learning-5b16a.appspot.com',
    measurementId: 'G-8YY4EE1HRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChMFm83B1mVecxWICyz6qcVcAGs07R7EA',
    appId: '1:81733342916:android:61159d9ca70d616b38db91',
    messagingSenderId: '81733342916',
    projectId: 'e-learning-5b16a',
    storageBucket: 'e-learning-5b16a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoCa_Dx27SDiTx61TwlKjstc-ZRVf79o',
    appId: '1:81733342916:ios:43f9fc19f0e6b83338db91',
    messagingSenderId: '81733342916',
    projectId: 'e-learning-5b16a',
    storageBucket: 'e-learning-5b16a.appspot.com',
    androidClientId: '81733342916-8o1nnposk7f6gn10lqrr9uu644j5h73s.apps.googleusercontent.com',
    iosClientId: '81733342916-u5m2orcbadso9vtfkl1c1j5oapdav7em.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningSeminar2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoCa_Dx27SDiTx61TwlKjstc-ZRVf79o',
    appId: '1:81733342916:ios:43f9fc19f0e6b83338db91',
    messagingSenderId: '81733342916',
    projectId: 'e-learning-5b16a',
    storageBucket: 'e-learning-5b16a.appspot.com',
    androidClientId: '81733342916-8o1nnposk7f6gn10lqrr9uu644j5h73s.apps.googleusercontent.com',
    iosClientId: '81733342916-u5m2orcbadso9vtfkl1c1j5oapdav7em.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningSeminar2023',
  );
}
